### ISSUE TITLE
Incorrect namespace

### ISSUE THREAD

**Issue by samczsun** [Serializator/NBTWrapper#1]
Should you be using the namespace of a domain you don't own?

**Comment by Serializator** [comment]
Your mom <3

**Comment by DarkSeraphim** [comment]
r00d

**Comment by Serializator** [comment]
![12745981_494079657438124_4353742764538112140_n](https://cloud.githubusercontent.com/assets/7153670/14972796/45bbebc6-10e0-11e6-8394-384f71394afa.jpg)
